### ISSUE TITLE
it brokey :(

### ISSUE THREAD

**Issue by Realswitzer** [daftieart/sneedbot#2]
```
switz@swotzterm cwd:sneedbot $ python3 sneedbot.py 
In the wise words of sneed, blessed is the man who seeds, who allows others to feed. And let us who follow Sneed, forgive the city slickers who fear those who possess the 4 of clubs. They are lost and instead follow the degenerate path of chuck, and his globohomo tendencies.
Ignoring exception in on_message
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/Users/sneeder/github/sneedbot/sneedbot.py", line 18, in on_message
    await message.add_reaction(":sneed:912786155886477383")
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/discord/message.py", line 1223, in add_reaction
    await self._state.http.add_reaction(self.channel.id, self.id, emoji)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/discord/http.py", line 254, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 10014): Unknown Emoji
Ignoring exception in on_message
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/Users/sneeder/github/sneedbot/sneedbot.py", line 18, in on_message
    await message.add_reaction(":sneed:912786155886477383")
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/discord/message.py", line 1223, in add_reaction
    await self._state.http.add_reaction(self.channel.id, self.id, emoji)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/discord/http.py", line 254, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 10014): Unknown Emoji
```

**Comment by Realswitzer** [comment]
had to switch emoji, plus your method of leaving a token in the code sucks
